spring.application.name=fitcare
server.port=${PORT:8081}

# ?? Clever Cloud MySQL ?????????????????????
spring.datasource.url=jdbc:mysql://buru9k6a7with6inwxh1-mysql.services.clever-cloud.com:3306/buru9k6a7with6inwxh1?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=u8tti57ijdgqpivv
spring.datasource.password=TKoMjxmOI4WhH3b6SCeE
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

# ? create first time to recreate tables
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

fitcare.jwt.secret=${JWT_SECRET}
fitcare.jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.fitcare=INFO
logging.level.org.springframework.security=WARN
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR